apiVersion: apps/v1
kind: Deployment
metadata:
  name: quote-db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: quote-db
  template:
    metadata:
      labels:
        app: quote-db
    spec:
      containers:
        - name: postgres
          image: postgres:14
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: "quotes"
            - name: POSTGRES_USER
              value: "postgres"
            - name: POSTGRES_PASSWORD
              value: "password"
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: db-storage
      volumes:
        - name: db-storage
          persistentVolumeClaim:
            claimName: db-pvc
